### ISSUE TITLE
feat(client): Archon Client Builder

### ISSUE THREAD

**Issue by refcell** [refcell/archon#1]
**Description**

There should be a `PipelineBuilder` that constructs the `Archon` pipeline.

In a very idiomatic syntax, the pipeline builder would take items that implement the `Stage` interface/trait and only accept stages that consume the previous stage's output channel.

**Comment by refcell** [comment]
Further, the pipeline wouldn't need to strictly hold stages, it could chain a series of channels and spawning functions to build synchronously constructible pipeline.

**Comment by literallymarvellous** [comment]
Hi, I took this on and open a pr.
